language: ruby
before_install:
  - gem update --system 2.1.11
  - gem --version
bundler_args: --without development
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-2.2.0
